language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install -q -r requirements/dev.txt --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - python manage.py test
  - coverage run --source=django_learning,blog manage.py test
env:
  - DJANGO=1.10
after_success: coveralls