# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='last_modification_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_modification_date',
            new_name='modified_at',
        ),
    ]
